version: '3.7'
services:
  vlogging_service:
    build:
      dockerfile: ./Dockerfile
      context: '.'
    restart: always
    # command: bash -c "/wait-for-it.sh --timeout=10 postgres:5432"
    # env_file:
    #   - './.env'
    ports:
      - '4000:4000'
    depends_on:
      - vlogs-db
    volumes:
      - .:/usr/src/app

  vlogs-db:
    image: postgres:9.6.19-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vlogs
    ports:
      - 5432:5432
    volumes:
      - .:/usr/src/pgdata/data
