version: '3.7'
services:
  vlogging_service:
    build:
      context: .
    ports:
      - 4000:4000
    depends_on:
      - vlogs-db
    volumes:
      - .:/usr/src/app

  vlogs-db:
    ports:
      - 5432:5432
    image: postgres:9.6.19-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vlog
    volumes:
      - .:/usr/src/pgdata/data
